"""empty message

Revision ID: 9d86d3b17fdb
Revises: 
Create Date: 2022-02-28 14:00:25.029976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d86d3b17fdb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_db2():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appmeta', sa.Column('name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade_db2():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appmeta', 'name')
    # ### end Alembic commands ###


def upgrade_db3():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_db3():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

